import AppStor from "../assets/images/images btns/app-store.svg";
import GooglePlay from "../assets/images/images btns/google-play.svg";
import Github from "../assets/images/images btns/github.svg";
import Web from "../assets/images/images btns/web-64.png";

import projImg1 from "../assets/images/image projects/project-1.jpg";
import projImg2 from "../assets/images/image projects/project-2.png";
import projImg3 from "../assets/images/image projects/project-3.jpg";

export const ListProjects = [

    {
        id: "01",
        title: "Project one",
        subDesc: "This is a system for visualizing attacks generated by IDS where this data is sent through the ELK stack to be processed, stored and finally visualized in a web dashboard so security engineers can have insights about their organization security.",
        imgUrl: projImg1,
        projectUrl: "",
        tags: {
            tags1: "ReactJs",
            tags2: "ChakraUi",
            tags3: "Swr",
        },
        bnts: {
            bntAppStor: {
                link: "",
                icon: AppStor
            },
            bntGoolePlay: {
                link: "",
                icon: GooglePlay
            },
            bntGithub: {
                link: "",
                icon: Github
            },
            bntWeb: {
                link: "",
                icon: Web
            },
        },
        desc: {
            line1: "Ansible: For task automation on the servers.",
            line2: "Docker for deploying the elastic stack.",
            line3: "Pfsense firewall",
            line4: "Suricata IDS.",
        },
    },
    {
        id: "02",
        title: "Project two",
        subDesc: "This is a system for visualizing attacks generated by IDS where this data is sent through the ELK stack to be processed, stored and finally visualized in a web dashboard so security engineers can have insights about their organization security.",
        imgUrl: projImg2,
        projectUrl: "",
        tags: {
            tags1: "ReactJs",
            tags2: "ChakraUi",
            tags3: "Swr",
        },
        bnts: {
            bntAppStor: {
                link: "",
                icon: AppStor
            },
            bntGoolePlay: {
                link: "",
                icon: GooglePlay
            },
            bntGithub: {
                link: "",
                icon: Github
            },
            bntWeb: {
                link: "",
                icon: Web
            },
        },
        desc: {
            line1: "Ansible: For task automation on the servers.",
            line2: "Docker for deploying the elastic stack.",
            line3: "Pfsense firewall",
            line4: "Suricata IDS.",
        },
    },
    {
        id: "03",
        title: "Project three",
        subDesc: "This is a system for visualizing attacks generated by IDS where this data is sent through the ELK stack to be processed, stored and finally visualized in a web dashboard so security engineers can have insights about their organization security.",
        imgUrl: projImg3,
        projectUrl: "",
        tags: {
            tags1: "ReactJs",
            tags2: "ChakraUi",
            tags3: "Swr",
        },
        bnts: {
            bntAppStor: {
                link: "",
                icon: AppStor
            },
            bntGoolePlay: {
                link: "",
                icon: GooglePlay
            },
            bntGithub: {
                link: "",
                icon: Github
            },
            bntWeb: {
                link: "",
                icon: Web
            },
        },
        desc: {
            line1: "Ansible: For task automation on the servers.",
            line2: "Docker for deploying the elastic stack.",
            line3: "Pfsense firewall",
            line4: "Suricata IDS.",
        },
    },

]